name: Generate changelog
on:
  release:
    types: [created, edited]
  push:
    branches:
      - "main"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "âœï¸ Generate release changelog"
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          headerLabel: "# ğŸ“‘ Changelog"
          addSections: '{"documentation":{"prefix":"### ğŸ“– Documentation","labels":["document"]},"Features":{"prefix":"### ğŸš€ Features","labels":["feature"]},"Enhancement":{"prefix":"### ğŸš€ Enhancement","labels":["enhancement"]},"bugfix":{"prefix":"ğŸ› Bug Fixes","labels":["bugfix"]},"refactor":{"prefix":"### ğŸ› refactor","labels":["refactor"]},"chore":{"prefix":"### ğŸ§° Chore","labels":["chore"]},"Otherchanges":{"prefix":"âœ¨ Other changes","labels":[""]},"dependencies":{"prefix":"â¬†ï¸ Dependency Updates","labels":["dependencies"]},"style":{"prefix":"ğŸŒˆ Style","labels":["style"]}}'
          author: true
          unreleased: true
          compareLink: true
          stripGeneratorNotice: false
          verbose: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USE_MILESTONE_TITLE: "false"
    - run: |
       ls -al
       cat ${{ github.workspace }}/CHANGELOG.md
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.TOKEN }}
        # path: ${{ github.workspace}}/axon
        signoff: false
        commit-message: "feat: automated pr to change config files"
        branch: bot-${{ github.repository }}
        title: "feat: automated pr to change log"
        body: "automated pr to change log"